# Generated by Django 4.2.1 on 2024-09-16 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.TextField(max_length=95)),
                ('introduction', models.TextField(max_length=330)),
                ('first_paragraph', models.TextField()),
                ('first_image', models.ImageField(blank=True, upload_to='article-img')),
                ('second_paragraph', models.TextField()),
                ('second_image', models.ImageField(blank=True, upload_to='article-img')),
                ('third_paragraph', models.TextField()),
                ('third_image', models.ImageField(blank=True, upload_to='article-img')),
                ('slug', models.SlugField(blank=True)),
                ('is_bestSeller', models.BooleanField(default=False)),
                ('num_of_reviews', models.PositiveBigIntegerField(default=0)),
                ('average_rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('card', models.CharField(default='regular', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('username', models.CharField(max_length=40)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)])),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='author-img')),
                ('name', models.CharField(max_length=70)),
                ('subject', models.ManyToManyField(to='articles.subject')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.author'),
        ),
        migrations.AddField(
            model_name='article',
            name='subject',
            field=models.ManyToManyField(to='articles.subject'),
        ),
    ]
