# Generated by Django 4.2.1 on 2024-09-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AngularLeafspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='angular-leafspot-img')),
            ],
        ),
        migrations.CreateModel(
            name='AnthracnoseFruitRot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='anthracnose-fruit-rot-img')),
            ],
        ),
        migrations.CreateModel(
            name='BlossomBlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='blossom-blight-img')),
            ],
        ),
        migrations.CreateModel(
            name='GrayMold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='gray-mold-img')),
            ],
        ),
        migrations.CreateModel(
            name='LeafSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='leaf-spot-img')),
            ],
        ),
        migrations.CreateModel(
            name='PowderyMildewFruit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='powdery-mildew-fruit-img')),
            ],
        ),
        migrations.CreateModel(
            name='PowderyMildewLeaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=43)),
                ('description', models.CharField(max_length=500)),
                ('image', models.ImageField(upload_to='powdery-mildew-leaf-img')),
            ],
        ),
    ]
